FROM node:20.9.0-alpine3.18

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm i

COPY backend/ .

RUN npm run build

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY backend/package.json .

ENV NODE_ENV=production
ENV DATABASE_URL=postgresql://user:password@db:5432/mydatabase

CMD [ "/home/node/app/.docker/command.sh" ]
